[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, elpass.xyz

[Rule]
# 1. 自动引用大牛每天维护的 Instagram 规则（自动更新）
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Instagram/Instagram.list,PROXY

# 2. 自动引用大牛每天维护的 TikTok 规则（自动更新）
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/TikTok/TikTok.list,PROXY

# 3. 基础分流（国内直连，其余全部走代理）
GEOIP,CN,DIRECT
FINAL,PROXY

https://ahrefs.com/writing-tools/paragraph-rewriter
# TikTok 免拔卡核心解锁脚本（目前欺骗系统为美国区 US）
(?<=_region=)CN(?=&) US 307
(?<=&mcc_mnc=)460[0-9]{2}(?=&) 310260 307
(?<=\?version_code=)1[0-9]\.[0-9]\.[0-9](?=&) 18.8.4 307

[MITM]
# 解密 TikTok 流量必填的主机名
hostname = *.tiktokv.com, *.byteoversea.com, *.tik-tokapi.com
