[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, elpass.xyz

[Rule]
DOMAIN-KEYWORD,instagram,PROXY
DOMAIN-SUFFIX,cdninstagram.com,PROXY
DOMAIN-KEYWORD,tiktokv,PROXY
DOMAIN-SUFFIX,byteoversea.com,PROXY
DOMAIN-SUFFIX,ibytedtos.com,PROXY
DOMAIN-SUFFIX,ipstatp.com,PROXY
DOMAIN-SUFFIX,muscdn.com,PROXY
DOMAIN-SUFFIX,tiktok.com,PROXY
DOMAIN-SUFFIX,tiktokcdn.com,PROXY
GEOIP,CN,DIRECT
FINAL,PROXY

https://ahrefs.com/writing-tools/paragraph-rewriter
(?<=_region=)CN(?=&) US 307
(?<=&mcc_mnc=)460[0-9]{2}(?=&) 310260 307
(?<=\?version_code=)1[0-9]\.[0-9]\.[0-9](?=&) 18.8.4 307

[MITM]
hostname = *.tiktokv.com, *.byteoversea.com, *.tik-tokapi.com
