[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, elpass.xyz

[Rule]
# Instagram 规则
DOMAIN-KEYWORD,instagram,PROXY
DOMAIN-SUFFIX,cdninstagram.com,PROXY

# TikTok 规则
DOMAIN-KEYWORD,tiktokv,PROXY
DOMAIN-SUFFIX,byteoversea.com,PROXY
DOMAIN-SUFFIX,ibytedtos.com,PROXY
DOMAIN-SUFFIX,ipstatp.com,PROXY
DOMAIN-SUFFIX,muscdn.com,PROXY
DOMAIN-SUFFIX,tiktok.com,PROXY
DOMAIN-SUFFIX,tiktokcdn.com,PROXY

# 基础直连与代理分流
GEOIP,CN,DIRECT
FINAL,PROXY

https://ahrefs.com/writing-tools/paragraph-rewriter
# TikTok 免拔卡解锁脚本（以欺骗系统为美国区 US 为例）
# 如果你想看日本区，可以把下方规则中的 US 改为 JP，或者中国台湾区改为 TW
(?<=_region=)CN(?=&) US 307
(?<=&mcc_mnc=)460[0-9]{2}(?=&) 310260 307
(?<=\?version_code=)1[0-9]\.[0-9]\.[0-9](?=&) 18.8.4 307

[MITM]
# 解密 TikTok 流量所需的主机名
hostname = *.tiktokv.com, *.byteoversea.com, *.tik-tokapi.com
